export const UserColumn = [
  {
    name: 'userName',
    required: true,
    label: 'Name',
    align: 'left',
    field: (row) => row.name,
    format: (val) => `${val}`,
    sortable: true,
  },
  {

    name: 'phone',
    align: 'center',
    label: 'Phone',
    field: 'rhone',
    sortable: true,
  },
  { name: 'role', label: 'Role', field: 'role', sortable: true },
  { name: 'assignShop', label: 'Shop', field: 'assignShop', sortable: true },
  { name: 'action', label: 'Action', field: 'action' },

];

export const UserRows = [
  {
    userName: 'Ali',
    phone: '+923086647777',
    role: 'admin',
    assignShop: 'Shop 1',
    outStandingBalance: 0,
    wholeSaleDiscount: 0,
    isActive: true,
    password: '12345678',
    customerGroup: 'group 1',
    isPhnNumberAsUserNumber: false,
    action: 'edit',
  },
  {
    userName: 'Ali',
    phone: '+923086647777',
    role: 'admin',
    assignShop: 'Shop 1',
    outStandingBalance: 0,
    wholeSaleDiscount: 0,
    isActive: true,
    password: '12345678',
    customerGroup: 'group 1',
    isPhnNumberAsUserNumber: false,
    action: 'edit',
  },
  {
    userName: 'Ali',
    phone: '+923086647777',
    role: 'admin',
    assignShop: 'Shop 1',
    outStandingBalance: 0,
    wholeSaleDiscount: 0,
    isActive: true,
    password: '12345678',
    customerGroup: 'group 1',
    isPhnNumberAsUserNumber: false,
    action: 'edit',
  },
  {
    userName: 'Ali',
    phone: '+923086647777',
    role: 'admin',
    assignShop: 'Shop 1',
    outStandingBalance: 0,
    wholeSaleDiscount: 0,
    isActive: true,
    password: '12345678',
    customerGroup: 'group 1',
    isPhnNumberAsUserNumber: false,
    action: 'edit',
  },
  {
    userName: 'Ali',
    phone: '+923086647777',
    role: 'admin',
    assignShop: 'Shop 1',
    outStandingBalance: 0,
    wholeSaleDiscount: 0,
    isActive: true,
    password: '12345678',
    customerGroup: 'group 1',
    isPhnNumberAsUserNumber: false,
    action: 'edit',
  },
  {
    userName: 'Ali',
    phone: '+923086647777',
    role: 'admin',
    assignShop: 'Shop 1',
    outStandingBalance: 0,
    wholeSaleDiscount: 0,
    isActive: true,
    password: '12345678',
    customerGroup: 'group 1',
    isPhnNumberAsUserNumber: false,
    action: 'edit',
  },
  {
    userName: 'Ali',
    phone: '+923086647777',
    role: 'admin',
    assignShop: 'Shop 1',
    outStandingBalance: 0,
    wholeSaleDiscount: 0,
    isActive: true,
    password: '12345678',
    customerGroup: 'group 1',
    isPhnNumberAsUserNumber: false,
    action: 'edit',
  },
  {
    userName: 'Ali',
    phone: '+923086647777',
    role: 'admin',
    assignShop: 'Shop 1',
    outStandingBalance: 0,
    wholeSaleDiscount: 0,
    isActive: true,
    password: '12345678',
    customerGroup: 'group 1',
    isPhnNumberAsUserNumber: false,
    action: 'edit',
  },
  {
    userName: 'Ali',
    phone: '+923086647777',
    role: 'admin',
    assignShop: 'Shop 1',
    outStandingBalance: 0,
    wholeSaleDiscount: 0,
    isActive: true,
    password: '12345678',
    customerGroup: 'group 1',
    isPhnNumberAsUserNumber: false,
    action: 'edit',
  },
  {
    userName: 'Ali',
    phone: '+923086647777',
    role: 'admin',
    assignShop: 'Shop 1',
    outStandingBalance: 0,
    wholeSaleDiscount: 0,
    isActive: true,
    password: '12345678',
    customerGroup: 'group 1',
    isPhnNumberAsUserNumber: false,
    action: 'edit',
  },
  {
    userName: 'Ali',
    phone: '+923086647777',
    role: 'admin',
    assignShop: 'Shop 1',
    outStandingBalance: 0,
    wholeSaleDiscount: 0,
    isActive: true,
    password: '12345678',
    customerGroup: 'group 1',
    isPhnNumberAsUserNumber: false,
    action: 'edit',
  },
];
