# .github/workflows/ci.yml

name: CI

on:
  push:
    branches:
      - '*'  # Run CI on all branches
  pull_request:
    branches:
      - master  # Run CI only on pull requests targeting the master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.16.1'  # Choose the appropriate Node.js version

      - name: Install dependencies and run tests
        run: |
          npm install
          npm run verify  # Replace with your test command
